### PR TITLE
Fix category_screen.dart

### PR DESCRIPTION
**Pull request by RubyGirl777**
Fixed the undefined error:
image

### CODE REVIEW

**Comment by mivoligo** [comment]
What Flutter version do you use?

**Comment by RubyGirl777** [comment]
I put the `flutter --version` command into my terminal and got this:
```
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (3 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

**Comment by mivoligo** [comment]
If you like, you can change to master with `flutter channel master` and then `flutter upgrade`. There is an important bug fix in master which makes navigating with keyboard possible on Linux.

**Comment by RubyGirl777** [comment]
Okay, I'll put in those commands and see the results.

**Comment by RubyGirl777** [comment]
image

**Comment by mivoligo** [comment]
OK, now, please check if you have the error with "label".

**Comment by RubyGirl777** [comment]
Nothing with label but now I have 98+ errors.

**Comment by RubyGirl777** [comment]
> Never mind the errors are gone.

I should probably close this PR.

**Comment by mivoligo** [comment]
OK

**Pull request closed without merging**
