### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by RubyGirl777**
Added MIT License to repo for others to see in the future.

### CODE REVIEW

**Comment by mivoligo** [comment]
Thanks for this but License is in devel channel. I'll merge all devel to master soon(ish).

**Comment by RubyGirl777** [comment]
Okay so should I close this?

**Comment by mivoligo** [comment]
Yes, please. And many thanks for your contributions :heart:

**Comment by RubyGirl777** [comment]
Your welcome.

**Pull request closed without merging**
